/**
 * terminalKeymap — macOS-style readline key bindings for the embedded `claude` TUI.
 *
 * xterm.js forwards raw arrow keys to the PTY but does NOT translate the Cmd/Option
 * arrow chords that iTerm/Terminal.app map to readline line/word motion, nor does it
 * emit a soft newline for Shift/Option+Enter — so word/line motion and newline-without
 * submit don't work in the embedded prompt. `mapTerminalKey` is the pure key→bytes
 * mapping wired via `term.attachCustomKeyEventHandler`: a non-null result is the byte
 * sequence to write to the PTY (and xterm's default is suppressed); null means "not
 * ours — let xterm handle it" so plain typing, Enter-submit, Ctrl-C and paste are
 * untouched (we only intercept the specific chords below).
 *
 * ## Interception note — keypress leak
 * xterm's `_keyDown` early-returns when the custom handler returns false, so no `\r`
 * leaks from that path. However xterm also calls the custom handler from `_keyPress`,
 * and the `_keyDownHandled` guard that would suppress `_keyPress` is only set when
 * `_keyDown` reaches its bottom (after the handler gate). For Shift+Enter the handler
 * returns false in `_keyDown` causing early return, so `_keyDownHandled` stays false
 * and `_keyPress` fires — calling this handler again with type `'keypress'`. We return
 * `''` (empty string, not null) for that case so `TerminalPanel` can see it, suppress
 * the send (nothing to write), and return false to xterm — blocking the leaked `\r`.
 */

/** The minimal slice of a KeyboardEvent the mapping needs (so it is node-testable). */
export interface TerminalKeyEvent {
  key: string
  metaKey: boolean
  altKey: boolean
  shiftKey: boolean
  ctrlKey: boolean
  type: string
  /**
   * True when the event is being generated by an IME composition in progress
   * (KeyboardEvent.isComposing). When true, we must NOT suppress the event —
   * xterm's CompositionHelper.keydown() must run to commit/finalize the pending
   * syllable; intercepting mid-composition leaves the textarea stale and causes
   * every subsequent keystroke to re-emit the last composed syllable.
   *
   * NOTE: on macOS/Electron the browser clears `isComposing` on the very keydown
   * that interrupts an active composition (e.g. Option+Left), so this flag alone is
   * not sufficient — see `textareaValue` below for the authoritative guard.
   */
  isComposing?: boolean
  /**
   * The legacy `KeyboardEvent.keyCode`. While an IME is mid-composition the browser
   * fires keydown with keyCode 229 ("process" key) — and crucially it does so even on
   * the keydown that COMMITS the syllable, where `isComposing` has already flipped back
   * to false. `isComposing` alone therefore misses that commit-keydown: if Option+Left
   * lands on it we'd intercept (return false), xterm early-returns before
   * CompositionHelper.keydown() runs, the textarea stays stale, and every later keystroke
   * re-emits the last composed syllable (the Korean "마지막 문자로 치환" corruption). So we
   * treat keyCode 229 as an additional "composition active" signal and defer to xterm.
   *
   * NOTE: for navigation keys that INTERRUPT composition (Option+Left/Right, Cmd+Left/Right),
   * the browser emits the key's own keyCode (e.g. 37 for ArrowLeft), NOT 229 — so this
   * guard also misses the interrupt case. Use `textareaValue` as the definitive check.
   */
  keyCode?: number
  /**
   * Whether a DOM composition session is currently active, tracked via explicit
   * `compositionstart` / `compositionend` listeners on `term.textarea` in TerminalPanel.
   *
   * This is the AUTHORITATIVE "is composition active right now?" signal. It is set to
   * `true` when `compositionstart` fires and back to `false` when `compositionend` fires
   * — with no stickiness. Contrast with `term.textarea.value`, which xterm only clears on
   * blur or CR/ETX: after a Korean composition ends the textarea still holds the committed
   * text ("테스트"), so a textareaValue check would permanently block Shift+Enter and other
   * chords until the next blur — a regression observed after the previous fix.
   *
   * Why this correctly fixes the Option+Left corruption (verified against xterm source):
   *   During the interrupt-keydown (Option+Left pressed mid-composition), `compositionstart`
   *   has fired but `compositionend` has NOT yet fired (compositionend fires AFTER the
   *   keydown that interrupts it). So `composing` is true → we return null → xterm's
   *   `_keyDown` is not short-circuited → `_compositionHelper.keydown()` runs at line 1032
   *   → `_finalizeComposition(false)` commits the pending syllables correctly.
   *   Once `compositionend` fires the ref immediately flips false → all chords (Shift+Enter,
   *   Option+Arrow, Cmd+Arrow) work normally again.
   *
   * Pass `compositionActiveRef.current` from TerminalPanel. Omitting / undefined is
   * treated the same as false (no active composition, proceed normally).
   */
  composing?: boolean
}

export const TERMINAL_KEY_SEQUENCES = {
  /** Cmd+Left → readline beginning-of-line (Ctrl-A). */
  lineStart: '\x01',
  /** Cmd+Right → readline end-of-line (Ctrl-E). */
  lineEnd: '\x05',
  /**
   * Option+Left → backward-word. Claude Code runs in CSI-u / kitty keyboard mode, where a
   * BARE `\x1bb` (ESC b) is ambiguous: the lone ESC is taken as a standalone Escape event and
   * the `b` lands separately, desyncing the prompt's cursor from the display — so after the
   * motion, typed chars corrupt the last character. Send the unambiguous modifier-encoded
   * Alt+Left instead (CSI 1 ; 3 D), which moves a word back AND keeps the insert cursor synced.
   */
  wordLeft: '\x1b[1;3D',
  /** Option+Right → forward-word — modifier-encoded Alt+Right (CSI 1 ; 3 C); see wordLeft. */
  wordRight: '\x1b[1;3C',
  /**
   * Shift+Enter → soft newline without submitting. Claude Code runs in kitty keyboard
   * protocol / CSI-u mode (`\x1b[>1u` sent on startup). In that mode Shift+Enter is
   * `CSI 13 ; 2 u`. The legacy `\x1b\r` (ESC+CR) is not recognised in CSI-u mode:
   * the bare ESC leaks into claude's readline and explains symptom #4 ("all but last
   * char submits").
   */
  newline: '\x1b[13;2u',
  /**
   * Alt/Option+Enter → same intent, CSI-u modifier bit 3.
   */
  altNewline: '\x1b[13;3u',
} as const

/**
 * Map a keyboard event to the PTY byte sequence to send, or null to defer to xterm.
 *
 * Return values:
 *  - non-empty string  → send this to the PTY; return false to xterm (suppress default)
 *  - ''  (empty string) → suppress xterm default but send nothing (used to block the
 *                          xterm keypress-leak for Enter chords; see module doc above)
 *  - null               → defer to xterm entirely (return true to xterm)
 *
 * Only the specific macOS chords are intercepted; everything else returns null so
 * existing terminal input behavior is preserved.
 */
export function mapTerminalKey(e: TerminalKeyEvent): string | null {
  // IME guard: defer to xterm whenever a DOM composition session is active.
  //
  // Primary signal:
  //   composing — set true on compositionstart, false on compositionend (tracked in
  //   TerminalPanel via a ref on term.textarea). This is the only signal that is both
  //   non-sticky (clears as soon as compositionend fires, unlike textarea.value which
  //   xterm only clears on blur/CR/ETX) AND present during the interrupt-keydown (unlike
  //   DOM isComposing, which macOS/Electron clears before the Option+Left keydown fires).
  //   See TerminalKeyEvent.composing JSDoc for the full xterm source trace.
  //
  // Belt-and-suspenders:
  //   isComposing — catches mid-composition character keydowns on non-macOS paths where
  //   the browser still reports true.
  //   keyCode === 229 — catches character IME commit-keydowns where isComposing already
  //   flipped false but 229 is still emitted (non-navigation IME entry).
  //
  // Without deferring, returning false causes CoreBrowserTerminal._keyDown to early-return
  // at lines 1025-1027, skipping _compositionHelper.keydown() at line 1032. That prevents
  // _finalizeComposition(false) from running, leaving the textarea stale and causing
  // compositionend to re-emit only the last syllable ("트" corruption).
  if (e.composing || e.isComposing || e.keyCode === 229) {
    return null
  }

  // Newline-without-submit: Shift+Enter or Option+Enter.
  // We intercept both keydown (to send the CSI-u sequence) AND keypress (to suppress
  // xterm's leaked \r — see module doc). Plain Enter (no modifier) is left to xterm.
  if (e.key === 'Enter' && (e.shiftKey || e.altKey)) {
    if (e.type === 'keydown') {
      return e.shiftKey ? TERMINAL_KEY_SEQUENCES.newline : TERMINAL_KEY_SEQUENCES.altNewline
    }
    // keypress or keyup: suppress xterm's \r leak but send nothing
    return ''
  }

  // Only act on keydown for everything below — keyup/keypress for the same chord
  // would double-send.
  if (e.type !== 'keydown') {
    return null
  }

  // Cmd+Arrow → line motion. Ignore if Option is also held (ambiguous chord).
  if (e.metaKey && !e.altKey) {
    if (e.key === 'ArrowLeft') return TERMINAL_KEY_SEQUENCES.lineStart
    if (e.key === 'ArrowRight') return TERMINAL_KEY_SEQUENCES.lineEnd
  }

  // Option+Arrow → word motion. Ignore if Cmd is also held.
  if (e.altKey && !e.metaKey) {
    if (e.key === 'ArrowLeft') return TERMINAL_KEY_SEQUENCES.wordLeft
    if (e.key === 'ArrowRight') return TERMINAL_KEY_SEQUENCES.wordRight
  }

  return null
}
